# Generated by Django 5.1 on 2024-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_tablebooking_event_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='timing',
            field=models.DateField(auto_now=True),
        ),
    ]
