# Generated by Django 5.1 on 2024-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tablebooking_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='timing',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
