# Generated by Django 5.1 on 2024-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tablebooking_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
