# Generated by Django 5.1 on 2024-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_eventschedule_date_remove_eventschedule_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='img',
            field=models.ImageField(upload_to='images/chefs/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to='images/menu_items/'),
        ),
    ]
