# Generated by Django 5.1 on 2024-10-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menu_calories_alter_chef_img_alter_event_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='table_id',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.table'),
        ),
    ]
