# Generated by Django 5.1 on 2024-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bookings_left',
            field=models.IntegerField(null=True),
        ),
    ]
